sudo: required
dist: trusty

language: node_js
node_js:
  - "8.2.1"

jobs:
  include:
    - stage: test
      script:
        - yarn test
    - stage: deploy
      script:
        - ng build --prod
        - firebase deploy --token $FIREBASE_TOKEN
