sudo: required
dist: trusty

language: node_js
node_js:
  - "8.2.1"

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: build prod
      script: ng build --prod
    - stage: deploy
      script: firebase deploy --token $FIREBASE_TOKEN
